import os

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
HUGGINGFACE_API_KEY = os.getenv("HUGGINGFACE_API_KEY", "")
AUDIO_INITIAL_DIR = os.getenv("AUDIO_INITIAL_DIR", "").strip()
WHISPER_MODEL = "whisper-large-v3-turbo"
LLM_MODEL = "llama-3.3-70b-versatile"
TRANSCRIPTION_PROVIDER = os.getenv(
    "TRANSCRIPTION_PROVIDER", "groq").strip().lower()
FASTER_WHISPER_MODEL = os.getenv("FASTER_WHISPER_MODEL", "small")
FASTER_WHISPER_DEVICE = os.getenv("FASTER_WHISPER_DEVICE", "auto")
FASTER_WHISPER_COMPUTE_TYPE = os.getenv(
    "FASTER_WHISPER_COMPUTE_TYPE", "int8")
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "groq").strip().lower()
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://127.0.0.1:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.2:3b")

TARGET_SUMMARY_WORDS_MIN = 1700
TARGET_SUMMARY_WORDS_MAX = 2200
TARGET_QUESTIONS = 16
TARGET_FLASHCARDS = 30
TARGET_GLOSSARY = 20
LLM_TEMP = 0.2
LLM_MAX_TOKENS = 4000
CHUNK_CHARLEN = 6000

UI_LANG = os.getenv("UI_LANG", "it")
